export const movieDetailDefault = {
  genres: [],
  runtime: 0,
  budget: 0,
  revenue: 0,
  overview: "",
  production_companie: [{ logo_path: "", name: "", id: 0, origin_country: "" }],
  trailer: {
    iso_639_1: "",
    iso_3166_1: "",
    name: "",
    key: "",
    site: "",
    size: 0,
    type: "",
    official: true,
    published_at: "",
    id: "",
  },
  id: 0,
  original_title: "",
  poster_path: "",
  release_date: "",
  vote_average: 0,
  vote_count: 0,
};
